# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/teaching',
                'doc_host': 'https://k111git.github.io',
                'git_url': 'https://github.com/k111git/teaching',
                'lib_path': 'teaching'},
  'syms': {'teaching.core': {'teaching.core.foo': ('core.html#foo', 'teaching/core.py')}}}